### PR TITLE
fix(TextMetrics): rtl direction + start/end textAlign

### LINKED ISSUE #2508: [BUG]: `measureText` not respecting `ctx.direction`
I have encountered this bug when using `ctx.direction = 'rtl'` and `ctx.textAlign = 'start' | 'end'`

It is clear that the code fails to first resolve `start`/`end` `textAlign` and therefore executes as if direction is `ltr`.

https://github.com/Automattic/node-canvas/blob/1234a86f65b2318906334ce0790cd12401c67a25/src/CanvasRenderingContext2d.cc#L2819-L2832

I am willing to PR.

### PR DESCRIPTION
**Pull request by ShaMan123**
Thanks for contributing!

- [x] Have you updated CHANGELOG.md?

closes #2508

### CODE REVIEW

**Review by ShaMan123 — COMMENTED** [review]
Is there any other test/thing I should add/do?

File: test/wpt/generated/the-canvas-element.js [hunk 1]
```diff
@@ -171,12 +171,6 @@ describe("WPT: the-canvas-element", function () {
 		assert.strictEqual(window.CanvasRenderingContext2D.prototype.fill, undefined, "window.CanvasRenderingContext2D.prototype.fill", "undefined")
 	});
 
-	it("2d.type class string", function () {
-		const canvas = createCanvas(100, 50);
-		const ctx = canvas.getContext("2d");
-		assert.strictEqual(Object.prototype.toString.call(ctx), '[object CanvasRenderingContext2D]')
```
Comment (chearon) [inline test/wpt/generated/the-canvas-element.js:177]: Did this need to be removed?

File: src/CanvasRenderingContext2d.cc [hunk 2]
```diff
@@ -2816,16 +2816,23 @@ Context2d::MeasureText(const Napi::CallbackInfo& info) {
...
   metrics = PANGO_LAYOUT_GET_METRICS(layout);
 
+  text_align_t alignment = state->textAlignment;
+
+  // Convert start/end to left/right based on direction
+  if (alignment == TEXT_ALIGNMENT_START) {
+    alignment = (state->direction == "rtl") ? TEXT_ALIGNMENT_RIGHT : TEXT_ALIGNMENT_LEFT;
+  } else if (alignment == TEXT_ALIGNMENT_END) {
+    alignment = (state->direction == "rtl") ? TEXT_ALIGNMENT_LEFT : TEXT_ALIGNMENT_RIGHT;
+  }
```
Comment (chearon) [inline src/CanvasRenderingContext2d.cc:2826]: Looks like this would be pretty easy to split out into a function since we do the exact same thing in `setTextPath`. What do you think?

File: test/wpt/text-styles.yaml [hunk 3]
```diff
@@ -503,13 +503,34 @@
...
+    ltrEndMetrics = ctx.measureText('hello');
+    assert.deepStrictEqual(ltrEndMetrics, rightMetrics, "ltr end metrics should equal right metrics");
+    	
+    ctx.direction = "rtl";
+    rtlEndMetrics = ctx.measureText('hello');
+    assert.deepStrictEqual(rtlEndMetrics, leftMetrics, "rtl end metrics should equal left metrics");
 
-    ctx.textAlign = "left"
-    metrics = ctx.measureText('hello');
-    @assert metrics.actualBoundingBoxLeft < metrics.actualBoundingBoxRight;
```
Comment (chearon) [inline test/wpt/text-styles.yaml:512]: I don't think this goes here. This test is imported from the [WPT tests](https://github.com/web-platform-tests/wpt/blob/ccaadde016187b16e607c6c6ae65e37089c452c5/html/canvas/tools/yaml/text.yaml#L522-L531), so it would get overwritten if they did any updates. You should be able to write this in `canvas.test.js` though.

**Review by chearon — CHANGES_REQUESTED** [review]
Thanks and I'm glad to see new tests! Need a couple of changes I think.

File: src/CanvasRenderingContext2d.cc (hunk 2 above)
Comment (ShaMan123) [reply src/CanvasRenderingContext2d.cc:2826]: Will do, not well versed in c++ but will manage

File: test/wpt/text-styles.yaml (hunk 3 above)
Comment (ShaMan123) [reply test/wpt/text-styles.yaml:512]: I thought the yaml files generate the js test files. Regardless I saw nothing runs these tests on CI

File: src/CanvasRenderingContext2d.cc [hunk 4]
```diff
@@ -2557,6 +2557,20 @@ inline double getBaselineAdjustment(PangoLayout* layout, short baseline) {
   }
 }
 
+text_align_t
```
Comment (ShaMan123) [inline src/CanvasRenderingContext2d.cc:2560]: Should I expose a strict text align enum?

```
enum text_align_strict_t : int8_t {
  STRICT_TEXT_ALIGNMENT_LEFT = TEXT_ALIGNMENT_LEFT,
  STRICT_TEXT_ALIGNMENT_CENTER = TEXT_ALIGNMENT_CENTER,
  STRICT_TEXT_ALIGNMENT_RIGHT = TEXT_ALIGNMENT_RIGHT
};

```

**Review by ShaMan123 — COMMENTED** [review]
I reverted the pwt changes in favor of the jest test and exposed `resolveTextAlignment` as requested

File: src/CanvasRenderingContext2d.cc (hunk 2 above)
Comment (ShaMan123) [reply src/CanvasRenderingContext2d.cc]: done

**Comment by ShaMan123** [comment]
@chearon ?

**Review by chearon — APPROVED** [review]
Looks great!
